rules:
  1:
    __class__: cat.nyaa.yasui.Rule
    enable: false
    condition: tps_1m >= 19.0 && tps_5m >= 19.0 && tps_15m >= 19.0
    enable_ai: '1'
  2:
    __class__: cat.nyaa.yasui.Rule
    enable: false
    condition: tps_1m < 18.0
    disable_ai: '1'
  tickspeed1:
    __class__: cat.nyaa.yasui.Rule
    enable: false
    condition: tps_1m > 19.0 && tps_5m > 19.0 && world_random_tick_speed < 3
    worlds:
      - world
      - world_nether
      - world_the_end
    world_random_tick_speed: MIN(world_random_tick_speed + 1,3)
    messageType: ACTION_BAR
    message: '&arandom tick speed&r: &9{world_random_tick_speed}'
  tickspeed2:
    __class__: cat.nyaa.yasui.Rule
    enable: false
    condition: tps_1m < 18.0 && tps_5m < 18.0 && world_random_tick_speed > 0
    worlds:
      - world
      - world_nether
      - world_the_end
    world_random_tick_speed: MAX(world_random_tick_speed - 1,0)
    messageType: ACTION_BAR
    message: '&arandom tick speed&r: &9{world_random_tick_speed}'