name: yasui
version: ${version}
main: cat.nyaa.yasui.Yasui
depend: [NyaaCore]
softdepend: [NyaaUtils,WorldEdit]
authors: [cylin]
api-version: 1.13
commands:
  yasui:
permissions:
  yasui.admin:
    default: op
  yasui.profiler:
    default: op